on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: dominicmh/hello-world-composite-action@main
        with:
          who-to-greet: "Mona the Octocat"
      - id: bar
        uses: ./.github/actions/nested@main
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
